### ISSUE TITLE
Use local OneAgent as in opentelemetry-metric-go

### ISSUE THREAD

**Issue by segfault16** [dynatrace-oss/opentelemetry-exporter-go#25]
Looking at https://github.com/dynatrace-oss/opentelemetry-metric-go it says:
````
// No options are required. By default, the exporter will attempt
  // to export to the local OneAgent endpoint.
  // If no OneAgent is running, or if you wish to export directly
  // to your Dynatrace cluster, APIToken and URL are required.
````

Why is this exporter different?
Can the traces be picked up by the local OneAgent?

**Comment by Kwintenvdb** [comment]
Hi there.
The package you linked is used for metrics only. This package can be used for OpenTelemetry-compatible traces. The traces will not be picked up by the local OneAgent. A Dynatrace endpoint must be configured, the traces will be exported automatically there.
